version: "3.9"

services:
  zep-graph:
    image: ghcr.io/mendoncart/zep-docker-graph-visualization:latest
      #  build: .
    container_name: zep-graph-visualization
    ports:
      - "3000:3000"
    environment:
      - ZEP_API_KEY=${ZEP_API_KEY}
    restart: unless-stopped
